<template>
  <v-container>
    <v-row>
      <v-col
        cols="12"
        sm="9"
        md="7"
      >
        <v-text-field
          ref="nome"
          v-model="nome"
          :value="pessoa.nome"
          :placeholder="pessoa.nome"
          :rules="nomeRules"
          :counter="50"
          label="Nome"
          filled
          outlined
          required
        />
      </v-col>

      <v-col
        cols="12"
        sm="5"
        md="3"
      >
        <v-text-field
          ref="rg"
          v-model="rg"
          v-mask="maskRG"
          :value="pessoa.rg"
          :placeholder="pessoa.rg"
          :rules="numeroRules"
          label="Registro geral"
          filled
          outlined
          required
        />
      </v-col>

      <v-col
        cols="12"
        sm="4"
        md="2"
      >
        <v-select
          v-model="nascionalidade"
          ref="nascionalidade"
          :value="pessoa.naturalidade"
          :placeholder="pessoa.naturalidade"
          :items="nascionalidades"
          :rules="[v => !!v || 'Nascionalidade é obrigatório']"
          label="País"
          filled
          outlined
          required
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  import { mask } from 'vue-the-mask'
  // import store from '../../store'

  export default {
    name: 'FormPessoa',
    directives: {
      mask,
    },
    props: [
      'pessoa',
    ],
    data: () => ({
      // valid: false,
      nome: '',
      rg: '',
      maskRG: '######################',
      nascionalidade: null,
      //  Regras de validação
      nomeRules: [
        v => !!v || 'Name is required',
        v => v.length <= 50 || 'Name must be less than 10 characters',
      ],
      numeroRules: [
        v => !!v || 'Name is required',
        v => v.length <= 22 || 'Name must be less than 10 characters',
      ],
      nascionalidades: [
        'ABW',
        'AFG',
        'AGO',
        'AIA',
        'ALA',
        'ALB',
        'AND',
        'ANT',
        'ARE',
        'ARG',
        'ARM',
        'ASM',
        'ATA',
        'ATF',
        'ATG',
        'AUS',
        'AUT',
        'AZE',
        'BDI',
        'BEL',
        'BEN',
        'BFA',
        'BGD',
        'BGR',
        'BHR',
        'BHS',
        'BIH',
        'BLM',
        'BLR',
        'BLZ',
        'BMU',
        'BOL',
        'BRA',
        'BRB',
        'BRN',
        'BTN',
        'BVT',
        'BWA',
        'CAF',
        'CAN',
        'CCK',
        'CHE',
        'CHL',
        'CHN',
        'CIV',
        'CMR',
        'COD',
        'COG',
        'COK',
        'COL',
        'COM',
        'CPV',
        'CRI',
        'CUB',
        'CUW',
        'CXR',
        'CYM',
        'CYP',
        'CZE',
        'DEU',
        'DJI',
        'DMA',
        'DNK',
        'DOM',
        'DZA',
        'ECU',
        'EGY',
        'ERI',
        'ESH',
        'ESP',
        'EST',
        'ETH',
        'FIN',
        'FJI',
        'FLK',
        'FRA',
        'FRO',
        'FSM',
        'GAB',
        'GBR',
        'GEO',
        'GGY',
        'GHA',
        'GIB',
        'GIN',
        'GLP',
        'GMB',
        'GNB',
        'GNQ',
        'GRC',
        'GRD',
        'GRL',
        'GTM',
        'GUF',
        'GUM',
        'GUY',
        'HKG',
        'HMD',
        'HND',
        'HRV',
        'HTI',
        'HUN',
        'IDN',
        'IMN',
        'IND',
        'IOT',
        'IRL',
        'IRN',
        'IRQ',
        'ISL',
        'ISR',
        'ITA',
        'JAM',
        'JEY',
        'JOR',
        'JPN',
        'KAZ',
        'KEN',
        'KGZ',
        'KHM',
        'KIR',
        'KNA',
        'KOR',
        'KWT',
        'LAO',
        'LBN',
        'LBR',
        'LBY',
        'LCA',
        'LIE',
        'LKA',
        'LSO',
        'LTU',
        'LUX',
        'LVA',
        'MAC',
        'MAF',
        'MAR',
        'MCO',
        'MDA',
        'MDG',
        'MDV',
        'MEX',
        'MHL',
        'MKD',
        'MLI',
        'MLT',
        'MMR',
        'MNE',
        'MNG',
        'MNP',
        'MOZ',
        'MRT',
        'MSR',
        'MTQ',
        'MUS',
        'MWI',
        'MYS',
        'MYT',
        'NAM',
        'NCL',
        'NER',
        'NFK',
        'NGA',
        'NIC',
        'NIU',
        'NLD',
        'NOR',
        'NPL',
        'NRU',
        'NZL',
        'OMN',
        'PAK',
        'PAN',
        'PCN',
        'PER',
        'PHL',
        'PLW',
        'PNG',
        'POL',
        'PRI',
        'PRK',
        'PRT',
        'PRY',
        'PSE',
        'PSL',
        'PYF',
        'QAT',
        'REU',
        'ROU',
        'RUS',
        'RWA',
        'SAU',
        'SDN',
        'SEN',
        'SGP',
        'SGS',
        'SHN',
        'SJM',
        'SLB',
        'SLE',
        'SLV',
        'SMR',
        'SOM',
        'SPM',
        'SRB',
        'STP',
        'SUR',
        'SVK',
        'SVN',
        'SWE',
        'SWZ',
        'SYC',
        'SYR',
        'TCA',
        'TCD',
        'TGO',
        'THA',
        'TJK',
        'TKL',
        'TKM',
        'TLS',
        'TON',
        'TTO',
        'TUN',
        'TUR',
        'TUV',
        'TWN',
        'TZA',
        'UGA',
        'UKR',
        'UMI',
        'URY',
        'USA',
        'UZB',
        'VAT',
        'VCT',
        'VEN',
        'VGB',
        'VIR',
        'VNM',
        'VUT',
        'WLF',
        'WSM',
        'YEM',
        'ZAF',
        'ZMB',
        'ZWE',
      ],
    }
    ),
    methods: {
      getPessoa () {
        return { nome: this.nome, rg: this.rg, nascionalidade: this.nascionalidade }
      },
    },
  }
</script>

<style>
</style>
